/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Trip */
        post: operations["create_trip_api_trips_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trip */
        get: operations["get_trip_api_trips__trip_id__get"];
        put?: never;
        post?: never;
        /** Delete Trip */
        delete: operations["delete_trip_api_trips__trip_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/places/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Places Search
         * @description Address autocomplete, via OneMap (I9).
         *
         *     A token failure is reported as a token failure — an empty list here would
         *     read as 'no such address', which is a different and misleading thing.
         */
        get: operations["places_search_api_places_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/destinations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Destinations */
        get: operations["destinations_api_destinations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trip Status */
        get: operations["trip_status_api_trips__trip_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scenario */
        get: operations["get_scenario_api_scenario_get"];
        put?: never;
        /** Set Scenario */
        post: operations["set_scenario_api_scenario_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}/alternatives": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trip Alternatives */
        get: operations["trip_alternatives_api_trips__trip_id__alternatives_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/push/key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Push Key
         * @description The browser needs the public key to subscribe. Never the private one.
         */
        get: operations["push_key_api_push_key_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/push/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Subscribe */
        post: operations["subscribe_api_push_subscribe_post"];
        /**
         * Unsubscribe
         * @description Unsubscribing also deletes her stored trips (privacy commitment 1).
         *
         *     `endpoint` is required. It used to be optional, and omitting it deleted
         *     every subscription on the server and every trip linked to them, unauthenticated
         *     (F04).
         */
        delete: operations["unsubscribe_api_push_subscribe_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/push/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Push Test
         * @description Fire the real check-and-send path now, so judges need not wait for 20:00.
         *
         *     If no browser has subscribed we still return the payload that *would* have
         *     been sent, rather than a bare success that shows nothing.
         *
         *     `trip_id` is required. Falling back to `all_trips()[0]` meant an anonymous
         *     caller acted on whichever trip happened to be first — pushing to its owner's
         *     phone and returning its id, which is enough to read her home coordinate (F05).
         */
        post: operations["push_test_api_push_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}/offline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Offline Bundle */
        get: operations["offline_bundle_api_trips__trip_id__offline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Attribution
         * @description Required wherever the map or anything derived from it is shown.
         *
         *     Omitting OSM attribution is a licence breach, not a style point
         *     (PS2_README.md:L290).
         */
        get: operations["attribution_api_attribution_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccessPoint */
        AccessPoint: {
            /** Exit Code */
            exit_code: string;
            /**
             * Status
             * @description What OSM knows about that door. `unknown` is not `no` (§6 limitation 5).
             * @enum {string}
             */
            status: "yes" | "no" | "unknown";
        } & {
            [key: string]: unknown;
        };
        /** Alternatives */
        Alternatives: {
            /** Trip Id */
            trip_id: string;
            disruption: components["schemas"]["Disruption"] | null;
            original: components["schemas"]["OriginalOption"];
            /** Options */
            options: (components["schemas"]["RailOption"] | components["schemas"]["BusOption"] | components["schemas"]["TaxiOption"])[];
            /** Not Offered */
            not_offered: components["schemas"]["NotOffered"][];
        } & {
            [key: string]: unknown;
        };
        /** Attribution */
        Attribution: {
            /**
             * Strings
             * @description Ready to display, in order.
             */
            strings: string[];
            osm: components["schemas"]["OsmAttribution"];
            lta: components["schemas"]["AttributionLink"];
            weather: components["schemas"]["AttributionLink"];
        } & {
            [key: string]: unknown;
        };
        /** AttributionLink */
        AttributionLink: {
            /** Text */
            text: string;
            /** Url */
            url: string;
        } & {
            [key: string]: unknown;
        };
        /** BusInfo */
        BusInfo: {
            /** Service No */
            service_no: string;
            /** Board Stop */
            board_stop: string;
            /** Board Stop Code */
            board_stop_code: string;
            /** Alight Stop */
            alight_stop: string;
            /** Alight Stop Code */
            alight_stop_code: string;
            /** Stops */
            stops: number | null;
            /** Distance Km */
            distance_km: number | null;
            /** Walk Min */
            walk_min: number | null;
            /** Ride Min */
            ride_min: number | null;
            /** Eta Min */
            eta_min: number | null;
            /** Eta Is Scheduled */
            eta_is_scheduled: boolean | null;
            /** Load */
            load: string | null;
            /** Load Label */
            load_label: string | null;
            /**
             * Wheelchair Accessible
             * @description Null when LTA does not say; drives `step_free` on the option.
             */
            wheelchair_accessible: boolean | null;
            /** Not Running */
            not_running: boolean | null;
            /** First Bus */
            first_bus: string | null;
            /** Last Bus */
            last_bus: string | null;
            /** Observed At */
            observed_at: string | null;
            /** Stale */
            stale: boolean | null;
        } & {
            [key: string]: unknown;
        };
        /** BusOption */
        BusOption: {
            /** Option Id */
            option_id: string;
            /** Label */
            label: string;
            /** Why */
            why: string;
            /** Delta Min */
            delta_min: number | null;
            /**
             * Step Free
             * @enum {string}
             */
            step_free: "yes" | "no" | "unknown";
            /**
             * Severity
             * @enum {string}
             */
            severity: "ok" | "info" | "warn" | "critical";
            /** Timing Basis */
            timing_basis: string;
            /** Legs */
            legs: unknown[];
            /** Rank */
            rank: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "bus";
            /** Duration Min */
            duration_min?: number | null;
            bus: components["schemas"]["BusInfo"];
        } & {
            [key: string]: unknown;
        };
        /** Checks */
        Checks: {
            /** Last Checked At */
            last_checked_at: string;
            /** Next Check At */
            next_check_at: string | null;
            /** Label */
            label: string;
        } & {
            [key: string]: unknown;
        };
        /** Crowd */
        Crowd: {
            /** Station Code */
            station_code: string | null;
            /** Station Name */
            station_name: string | null;
            /** Level */
            level: string;
            /** Label */
            label: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "ok" | "info" | "warn" | "critical";
            /**
             * Window
             * @description [start, end] of the 10-minute bucket; null when the row omits them.
             */
            window: (string | null)[];
            /**
             * Source
             * @enum {string}
             */
            source: "live" | "simulated";
            /** Stale */
            stale: boolean;
            /** Observed At */
            observed_at: string;
        } & {
            [key: string]: unknown;
        };
        /** DeletedTrip */
        DeletedTrip: {
            /** Deleted */
            deleted: boolean;
            /** Note */
            note: string;
        } & {
            [key: string]: unknown;
        };
        /** Destination */
        Destination: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Block */
            block: string;
            /** Coord */
            coord: number[];
        } & {
            [key: string]: unknown;
        };
        /** Destinations */
        Destinations: {
            /** Destinations */
            destinations: components["schemas"]["Destination"][];
        } & {
            [key: string]: unknown;
        };
        /** Disruption */
        Disruption: {
            /** Line */
            line: string | null;
            /**
             * Severity
             * @enum {string}
             */
            severity: "ok" | "info" | "warn" | "critical";
            /** Headline */
            headline: string;
            /** Detail */
            detail: string;
            /** Delay Min */
            delay_min: number | null;
            /** Delay Basis */
            delay_basis: string | null;
            /** Affected Stations */
            affected_stations: string[];
            /** On Her Route */
            on_her_route: boolean;
            /** Free Bus Available */
            free_bus_available: boolean;
            /** Free Bus Islandwide */
            free_bus_islandwide: boolean;
            /**
             * Source
             * @enum {string}
             */
            source: "live" | "simulated";
            /** Observed At */
            observed_at: string;
            /** Stale */
            stale: boolean;
            /** Simulated Note */
            simulated_note?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** ErrorBody */
        ErrorBody: {
            /**
             * Code
             * @description Machine-readable; the §1 enum.
             */
            code: string;
            /**
             * Message
             * @description Shown to the user as written.
             */
            message: string;
            /**
             * Retryable
             * @description Whether the same call may succeed later.
             */
            retryable: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        } & {
            [key: string]: unknown;
        };
        /** FeatureCollection */
        FeatureCollection: {
            /**
             * Type
             * @constant
             */
            type: "FeatureCollection";
            /** Features */
            features: components["schemas"]["MapFeature"][];
        } & {
            [key: string]: unknown;
        };
        /** Health */
        Health: {
            /** Ok */
            ok: boolean;
            /** Graph Built At */
            graph_built_at: string;
            /** Stations */
            stations: number;
            /** @description Whether each credential is present — never its value. */
            credentials: components["schemas"]["HealthCredentials"];
            /**
             * Fixtures Only
             * @description True when the server is serving recorded upstream responses.
             */
            fixtures_only: boolean;
        } & {
            [key: string]: unknown;
        };
        /** HealthCredentials */
        HealthCredentials: {
            /** Lta Account Key */
            lta_account_key: boolean;
            /** Onemap Token */
            onemap_token: boolean;
        } & {
            [key: string]: unknown;
        };
        /** LegAccess */
        LegAccess: {
            board_at: components["schemas"]["AccessPoint"];
            alight_at: components["schemas"]["AccessPoint"];
        } & {
            [key: string]: unknown;
        };
        /** LegPoint */
        LegPoint: {
            /** Name */
            name: string;
            /** Coord */
            coord: number[];
            /** Station Code */
            station_code?: string | null;
            /**
             * Exit Code
             * @description Rendered form, e.g. "Exit 6".
             */
            exit_code?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** LiftAlert */
        LiftAlert: {
            /** Station Code */
            station_code: string;
            /** Station Name */
            station_name: string;
            /** Station Id */
            station_id: string | null;
            /** Line */
            line: string | null;
            /**
             * Exit Code
             * @description First blocked exit, or null when the description named none.
             */
            exit_code: string | null;
            /**
             * Blocked Exit Refs
             * @description Every exit the outage takes out. Read this, not `exit_code`, to decide where she may walk (F02).
             */
            blocked_exit_refs: string[];
            /** Lift Id */
            lift_id: string | null;
            /**
             * Lift Desc
             * @description Upstream text, unedited.
             */
            lift_desc: string;
            /**
             * Resolution
             * @description How confidently the description was matched.
             */
            resolution: string;
            /** Parsed Exits */
            parsed_exits: string[];
            /** Line Prefix */
            line_prefix: string | null;
            /**
             * Severity
             * @enum {string}
             */
            severity: "ok" | "info" | "warn" | "critical";
            /** Label */
            label: string;
            /** Detail */
            detail: string;
            /** Affects Route */
            affects_route: boolean;
            /**
             * Source
             * @enum {string}
             */
            source: "live" | "simulated";
            /** Observed At */
            observed_at: string;
            /** Stale */
            stale: boolean;
            /**
             * Simulated Note
             * @description Present only on simulated rows; must be displayed.
             */
            simulated_note?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** LineRef */
        LineRef: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Colour */
            colour: string;
        } & {
            [key: string]: unknown;
        };
        /** LineString */
        LineString: {
            /**
             * Type
             * @constant
             */
            type: "LineString";
            /**
             * Coordinates
             * @description [lon, lat] pairs, in walking order.
             */
            coordinates: number[][];
        } & {
            [key: string]: unknown;
        };
        /** MapFeature */
        MapFeature: {
            /**
             * Type
             * @constant
             */
            type: "Feature";
            properties: components["schemas"]["MapFeatureProperties"];
            geometry: components["schemas"]["LineString"];
        } & {
            [key: string]: unknown;
        };
        /** MapFeatureProperties */
        MapFeatureProperties: {
            /** Leg Id */
            leg_id: string;
            /** Mode */
            mode: string;
        } & {
            [key: string]: unknown;
        };
        /** NotOffered */
        NotOffered: {
            /** Label */
            label: string;
            /** Why Not */
            why_not: string;
            /** Note */
            note?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** OfflineBundle */
        OfflineBundle: {
            /** Trip Id */
            trip_id: string;
            /** Generated At */
            generated_at: string;
            plan: components["schemas"]["OfflinePlan"];
            /** @description Null when status could not be read; see `warnings`. */
            status_snapshot?: components["schemas"]["RouteStatus"] | null;
            /**
             * Steps Plain
             * @description The route in words, for no-map use.
             */
            steps_plain: string[];
            tiles: components["schemas"]["Tiles"];
            /**
             * Warnings
             * @description Never serves written steps without either a snapshot or a warning.
             */
            warnings: string[];
            /** Offline Notice */
            offline_notice: string;
            /** Attribution */
            attribution: string[];
        } & {
            [key: string]: unknown;
        };
        /**
         * OfflinePlan
         * @description The stored plan as the bundle carries it: no `trip_id`, plus replan state.
         */
        OfflinePlan: {
            /** Trip Id */
            trip_id?: string | null;
            /** Appointment At */
            appointment_at: string;
            summary: components["schemas"]["PlanSummary"];
            /** Legs */
            legs: (components["schemas"]["WalkLeg"] | components["schemas"]["RailLeg"])[];
            map: components["schemas"]["TripMap"];
            /** Attribution */
            attribution: string[];
            /** Rerouted */
            rerouted?: boolean | null;
            /** Replan Failed */
            replan_failed?: boolean | null;
            /** Blocked Signature */
            blocked_signature?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** Origin */
        Origin: {
            /**
             * Label
             * @default Blk 208B New Upper Changi Road
             */
            label: string;
            /** Coord */
            coord?: number[];
        };
        /** OriginalOption */
        OriginalOption: {
            /** Label */
            label: string;
            /** Duration Min */
            duration_min: number | null;
            /** Arrival At */
            arrival_at: string | null;
            /** Viable */
            viable: boolean;
            /**
             * Step Free
             * @enum {string}
             */
            step_free: "yes" | "no" | "unknown";
            /** Note */
            note: string;
        } & {
            [key: string]: unknown;
        };
        /** OsmAttribution */
        OsmAttribution: {
            /** Text */
            text: string;
            /** Url */
            url: string;
            /** Licence */
            licence: string;
        } & {
            [key: string]: unknown;
        };
        /** Overall */
        Overall: {
            /**
             * Severity
             * @enum {string}
             */
            severity: "ok" | "info" | "warn" | "critical";
            /** Headline */
            headline: string;
            /** Detail */
            detail: string;
            action?: components["schemas"]["OverallAction"] | null;
        } & {
            [key: string]: unknown;
        };
        /** OverallAction */
        OverallAction: {
            /** Kind */
            kind: string;
            /** Label */
            label: string;
        } & {
            [key: string]: unknown;
        };
        /** Place */
        Place: {
            /** Label */
            label: string;
            /** Address */
            address: string;
            /**
             * Postal
             * @description Null when OneMap says NIL.
             */
            postal?: string | null;
            /** Coord */
            coord: number[];
        } & {
            [key: string]: unknown;
        };
        /** PlaceSearch */
        PlaceSearch: {
            /** Results */
            results: components["schemas"]["Place"][];
            /**
             * Source
             * @description Absent for an empty query.
             */
            source?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** PlanSummary */
        PlanSummary: {
            /** Leave By */
            leave_by: string;
            /** Leave By Label */
            leave_by_label: string;
            /**
             * Arrival Window
             * @description [earliest, latest] ISO-8601.
             */
            arrival_window: string[];
            /** Arrival Label */
            arrival_label: string;
            /** Appointment Label */
            appointment_label: string;
            /** Buffer Min */
            buffer_min: number;
            /** Duration Min */
            duration_min: number;
            /**
             * Range Min
             * @description [fast, slow] minutes.
             */
            range_min: number[];
            /**
             * Timing Basis
             * @description Why the number is what it is, in a sentence.
             */
            timing_basis: string;
            /**
             * Step Free
             * @enum {string}
             */
            step_free: "yes" | "no" | "unknown";
            /** Sheltered Pct */
            sheltered_pct: number;
            /** Walk Distance M */
            walk_distance_m: number;
        } & {
            [key: string]: unknown;
        };
        /** Preferences */
        Preferences: {
            /**
             * Walking Pace
             * @default slow
             * @enum {string}
             */
            walking_pace: "slow" | "normal";
            /**
             * Avoid Stairs
             * @default true
             */
            avoid_stairs: boolean;
            /**
             * Prefer Sheltered
             * @default true
             */
            prefer_sheltered: boolean;
            /**
             * Buffer Min
             * @default 15
             */
            buffer_min: number;
        };
        /** PushKey */
        PushKey: {
            /** Public Key */
            public_key: string;
        } & {
            [key: string]: unknown;
        };
        /** PushPayload */
        PushPayload: {
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Trip Id */
            trip_id: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "ok" | "info" | "warn" | "critical";
            /** Url */
            url: string;
            /** Digest */
            digest?: string | null;
            /** Sent At */
            sent_at?: string | null;
            /** Source */
            source?: string | null;
            /** Simulated Note */
            simulated_note?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** PushResult */
        PushResult: {
            /**
             * Endpoint
             * @description Truncated; never the full endpoint.
             */
            endpoint: string;
            /** Sent */
            sent: boolean;
            /**
             * Error
             * @description A code (`PUSH_FAILED`, `ENDPOINT_NOT_ALLOWED`, `ENDPOINT_GONE`, `PUSH_NOT_CONFIGURED`), never the upstream body (F03).
             */
            error?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** PushTest */
        PushTest: {
            /** Sent */
            sent: boolean;
            /** Subscriptions */
            subscriptions: number;
            /** Results */
            results: components["schemas"]["PushResult"][];
            /** @description What would have been sent, so it is readable without a paired device. */
            payload: components["schemas"]["PushPayload"];
            /** Note */
            note?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** RailLeg */
        RailLeg: {
            /** Leg Id */
            leg_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "rail";
            from: components["schemas"]["LegPoint"];
            to: components["schemas"]["LegPoint"];
            line: components["schemas"]["LineRef"];
            /** Duration Min */
            duration_min: number | null;
            /**
             * Headway Min
             * @description Measured at the hour she boards, not the appointment's (F27).
             */
            headway_min: number | null;
            /** Instruction */
            instruction: string;
            /**
             * Step Free
             * @enum {string}
             */
            step_free: "yes" | "no" | "unknown";
            access: components["schemas"]["LegAccess"];
            geometry: components["schemas"]["LineString"];
        } & {
            [key: string]: unknown;
        };
        /** RailOption */
        RailOption: {
            /** Option Id */
            option_id: string;
            /** Label */
            label: string;
            /** Why */
            why: string;
            /** Delta Min */
            delta_min: number | null;
            /**
             * Step Free
             * @enum {string}
             */
            step_free: "yes" | "no" | "unknown";
            /**
             * Severity
             * @enum {string}
             */
            severity: "ok" | "info" | "warn" | "critical";
            /** Timing Basis */
            timing_basis: string;
            /** Legs */
            legs: unknown[];
            /** Rank */
            rank: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "rail";
            /** Leave By */
            leave_by?: string | null;
            /** Leave By Label */
            leave_by_label?: string | null;
            /** Arrival At */
            arrival_at?: string | null;
            /** Duration Min */
            duration_min?: number | null;
            /**
             * Viable
             * @description False when the suggested departure has already passed.
             */
            viable?: boolean | null;
        } & {
            [key: string]: unknown;
        };
        /** RouteStatus */
        RouteStatus: {
            /** Trip Id */
            trip_id: string;
            overall: components["schemas"]["Overall"];
            /** Lift Alerts */
            lift_alerts: components["schemas"]["LiftAlert"][];
            /** @description Null on a quiet day — there is no advisory to report. */
            disruption: components["schemas"]["Disruption"] | null;
            /** Crowd */
            crowd: components["schemas"]["Crowd"][];
            /** @description Null when the nowcast could not be read at all; the rest of the overlay is still served. */
            weather: components["schemas"]["Weather"] | null;
            checks: components["schemas"]["Checks"];
            /**
             * Rerouted
             * @description The stored plan was rebuilt because an outage blocked a door it used.
             */
            rerouted: boolean;
            /**
             * Replan Failed
             * @description Every step-free entrance is out and no route could be built.
             */
            replan_failed: boolean;
            /** Stale */
            stale: boolean;
            /** Observed At */
            observed_at: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * ScenarioFlags
         * @description The demo switches, in the shape `GET /api/scenario` returns them.
         */
        ScenarioFlags: {
            /** Lift Outage Outram */
            lift_outage_outram?: boolean | null;
            /** Ewl Disruption */
            ewl_disruption?: boolean | null;
        };
        /** ScenarioFlagsOut */
        ScenarioFlagsOut: {
            /** Lift Outage Outram */
            lift_outage_outram: boolean;
            /** Ewl Disruption */
            ewl_disruption: boolean;
        } & {
            [key: string]: unknown;
        };
        /**
         * ScenarioRequest
         * @description Either the flat body or the nested one `GET /api/scenario` returns.
         *
         *     The nested shape is what contract §8 documents and what a screen already
         *     holds after reading the state, so posting it back has to work. It used to
         *     return `200` and change nothing: the field did not exist, and Pydantic
         *     dropped it silently. That is the worst failure available to an API — the
         *     caller is told it succeeded.
         *
         *     `extra="forbid"` closes the same trap for typos: `{"lift_outage": true}`
         *     is now a `422` naming the field rather than a cheerful no-op.
         */
        ScenarioRequest: {
            /** Enabled */
            enabled?: boolean | null;
            scenarios?: components["schemas"]["ScenarioFlags"] | null;
            /** Lift Outage Outram */
            lift_outage_outram?: boolean | null;
            /** Ewl Disruption */
            ewl_disruption?: boolean | null;
            /** Note */
            note?: string | null;
        };
        /** ScenarioState */
        ScenarioState: {
            /**
             * Enabled
             * @description The master switch. `_on()` reads this and the flag.
             */
            enabled: boolean;
            scenarios: components["schemas"]["ScenarioFlagsOut"];
            /** Note */
            note: string;
        } & {
            [key: string]: unknown;
        };
        /** SubscribeRequest */
        SubscribeRequest: {
            subscription: components["schemas"]["Subscription"];
            /**
             * Trip Ids
             * @default []
             */
            trip_ids: string[];
        };
        /** Subscribed */
        Subscribed: {
            /** Subscribed */
            subscribed: boolean;
            /**
             * Checks
             * @description The checks this subscription will receive.
             */
            checks: string[];
        } & {
            [key: string]: unknown;
        };
        /** Subscription */
        Subscription: {
            /** Endpoint */
            endpoint: string;
            /** Keys */
            keys: {
                [key: string]: unknown;
            };
        };
        /** TaxiOption */
        TaxiOption: {
            /** Option Id */
            option_id: string;
            /** Label */
            label: string;
            /** Why */
            why: string;
            /** Delta Min */
            delta_min: number | null;
            /**
             * Step Free
             * @enum {string}
             */
            step_free: "yes" | "no" | "unknown";
            /**
             * Severity
             * @enum {string}
             */
            severity: "ok" | "info" | "warn" | "critical";
            /** Timing Basis */
            timing_basis: string;
            /** Legs */
            legs: unknown[];
            /** Rank */
            rank: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "taxi";
            /** Duration Min */
            duration_min?: number | null;
            taxi_stand: components["schemas"]["TaxiStand"];
        } & {
            [key: string]: unknown;
        };
        /** TaxiStand */
        TaxiStand: {
            /** Name */
            name: string | null;
            /** Coord */
            coord: number[];
            /** Distance M */
            distance_m: number | null;
            /** Barrier Free */
            barrier_free: boolean | null;
            /** Fare Estimate */
            fare_estimate: string | null;
            /**
             * Anchor
             * @description Which end of the journey the stand is measured from.
             */
            anchor: string;
        } & {
            [key: string]: unknown;
        };
        /** Tiles */
        Tiles: {
            /** Style Url */
            style_url: string | null;
            /** Tile Pack Url */
            tile_pack_url: string | null;
            /** Attribution */
            attribution: string;
            /** Zoom Range */
            zoom_range: number[];
            /**
             * Unavailable Reason
             * @description Why there is no tile pack, so the screen can say so.
             */
            unavailable_reason: string | null;
        } & {
            [key: string]: unknown;
        };
        /** TripMap */
        TripMap: {
            /**
             * Bbox
             * @description [west, south, east, north].
             */
            bbox: number[];
            geometry: components["schemas"]["FeatureCollection"];
        } & {
            [key: string]: unknown;
        };
        /** TripPlan */
        TripPlan: {
            /** Trip Id */
            trip_id: string;
            /** Appointment At */
            appointment_at: string;
            summary: components["schemas"]["PlanSummary"];
            /** Legs */
            legs: (components["schemas"]["WalkLeg"] | components["schemas"]["RailLeg"])[];
            map: components["schemas"]["TripMap"];
            /** Attribution */
            attribution: string[];
        } & {
            [key: string]: unknown;
        };
        /** TripRequest */
        TripRequest: {
            origin?: components["schemas"]["Origin"];
            /**
             * Destination Id
             * @default SGH
             */
            destination_id: string;
            /**
             * Appointment At
             * Format: date-time
             */
            appointment_at: string;
            preferences?: components["schemas"]["Preferences"];
        };
        /** Unsubscribed */
        Unsubscribed: {
            /** Unsubscribed */
            unsubscribed: boolean;
            /** Subscriptions Removed */
            subscriptions_removed: number;
            /** Trips Removed */
            trips_removed: number;
            /** Note */
            note: string;
        } & {
            [key: string]: unknown;
        };
        /** WalkLeg */
        WalkLeg: {
            /** Leg Id */
            leg_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "walk";
            from: components["schemas"]["LegPoint"];
            to: components["schemas"]["LegPoint"];
            /** Duration Min */
            duration_min: number;
            /** Distance M */
            distance_m: number;
            /** Covered M */
            covered_m: number;
            /** Instruction */
            instruction: string;
            /**
             * Step Free
             * @enum {string}
             */
            step_free: "yes" | "no" | "unknown";
            /** Surface Warnings */
            surface_warnings: string[];
            geometry: components["schemas"]["LineString"];
        } & {
            [key: string]: unknown;
        };
        /** Weather */
        Weather: {
            /** Rain Expected */
            rain_expected: boolean;
            /** Areas */
            areas: components["schemas"]["WeatherArea"][];
            /** Label */
            label: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "ok" | "info" | "warn" | "critical";
            /** Affects Route */
            affects_route: boolean;
            /**
             * Source
             * @enum {string}
             */
            source: "live" | "simulated";
            /** Stale */
            stale: boolean;
            /** Observed At */
            observed_at: string;
        } & {
            [key: string]: unknown;
        };
        /** WeatherArea */
        WeatherArea: {
            /**
             * Name
             * @description Null when the nowcast carried no areas — an upstream outage.
             */
            name: string | null;
            /**
             * For
             * @description Which end of the trip this area covers.
             */
            for: string;
            /**
             * Distance Km
             * @description Null when no area could be placed — the distance is then unbounded.
             */
            distance_km: number | null;
            /** Forecast */
            forecast: string | null;
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_trip_api_trips_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripPlan"];
                };
            };
            /** @description The §1 error envelope. */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The §1 error envelope. */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_trip_api_trips__trip_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripPlan"];
                };
            };
            /** @description The §1 error envelope. */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The §1 error envelope. */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_trip_api_trips__trip_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletedTrip"];
                };
            };
            /** @description The §1 error envelope. */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The §1 error envelope. */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    places_search_api_places_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceSearch"];
                };
            };
            /** @description The §1 error envelope. */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The §1 error envelope. */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    destinations_api_destinations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Destinations"];
                };
            };
            /** @description The §1 error envelope. */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The §1 error envelope. */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    trip_status_api_trips__trip_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteStatus"];
                };
            };
            /** @description The §1 error envelope. */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The §1 error envelope. */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_scenario_api_scenario_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioState"];
                };
            };
            /** @description The §1 error envelope. */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The §1 error envelope. */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    set_scenario_api_scenario_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioState"];
                };
            };
            /** @description The §1 error envelope. */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The §1 error envelope. */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    trip_alternatives_api_trips__trip_id__alternatives_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alternatives"];
                };
            };
            /** @description The §1 error envelope. */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The §1 error envelope. */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    push_key_api_push_key_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushKey"];
                };
            };
            /** @description The §1 error envelope. */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The §1 error envelope. */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    subscribe_api_push_subscribe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscribeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscribed"];
                };
            };
            /** @description The §1 error envelope. */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The §1 error envelope. */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    unsubscribe_api_push_subscribe_delete: {
        parameters: {
            query: {
                endpoint: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Unsubscribed"];
                };
            };
            /** @description The §1 error envelope. */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The §1 error envelope. */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    push_test_api_push_test_post: {
        parameters: {
            query: {
                trip_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushTest"];
                };
            };
            /** @description The §1 error envelope. */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The §1 error envelope. */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    offline_bundle_api_trips__trip_id__offline_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfflineBundle"];
                };
            };
            /** @description The §1 error envelope. */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The §1 error envelope. */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    attribution_api_attribution_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attribution"];
                };
            };
        };
    };
}
